### ISSUE TITLE
[travis ci - blog] email -> slack으로 변경

### ISSUE THREAD

**Issue by richellin** [kodevops/guideline#31]
- [x] [Add travis app on slack](https://kodevelopers.slack.com/services/B016QSPEHPG)
- [x] [Fix .travis.yml](https://github.com/kodevops/blog/blob/master/.travis.yml#L42-L44)

**Comment by richellin** [comment]
> notifications.slack.rooms: using a plain string on a key that expects an encrypted string

흠.. 퍼블릭 레포지토리라서 암호화가 필수 인가보네.. ㅠ_ㅠ  암호화를 한뒤에 변수에 저장 하도록 조사...하기

**Comment by richellin** [comment]
https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications

1. gem install travis --no-document
2. travis encrypt "<account>:<token>" --add notifications.slack.rooms
3. change key to encrypted string as below
```yaml
# before
slack: kodevelopers:$SLACK_TOKEN

# after
slack:
    rooms:
      secure: Lh+6u8vBbOXTUdeVvYwS1WL26kjT8wKxHLUEF03TGqTb3gWXBB+0MYgHqXACujMf5mQnIFMJlSDQsC4lZH5weKD7qWy8NquCUIYjIqGY200HuSQMIF8uVTYtWHHapAG5hl8KW+0fwbwHsEw8z5fuY2UY8A8Vdy/FZzphpXpe95XTNC7kVH5hViNimUaQ69Ei9g2QFc7he8l3bbTthXrW1FjnijgfsdMNqJT8UWv9/tiaYwNf3oaN2crEnMPgi4Gtu/jkFwZKSoLY9ZVyiMA1VcrhIher/qcGQVozBN5YZC0eZgY8tqzrN0xjOJYZK4SMXRzW1lR/gdl0Fa7M7EXUZ6pRWpeqgb1oIoXZp6kyZAB05tOdW5fsL37VLoEHLJ7qwzX2U176tR+KeNLdgaU3YxaEDYkvGDWgH3SN4jfbDG/Gx2Jk81cYKB6myMQTGTNdEyG0CA31cYozJ7FAESdt/FuA0byhq0XFIh8M6mD7j5yu++y2xrzzpXS2X/oZN+tNLXl/ffuuJAuTCvfeAF34CZjArUKjYiS0lbIZUEUCeuQgcqEk3Rx2KWl7bS3eTpkCkiYGbbPHBy4wZcUyE4NN3vCV84xx1NPJIPRsSkZKySOvKk8JQiYayYr3Tiyk/XktEfXBU74tUC+4jThATTTnji4Sp9V71bZOV0boHfieDi8=
```
